export enum BookingStateActionType {
  SET_SERVICES = 'SET_SERVICES',
  SET_STAFF = 'SET_STAFF',
  SET_DATE = 'SET_DATE',
  SET_TIMESLOT = 'SET_TIMESLOT',
  RESET_BOOKING_STATE = 'RESET_BOOKING_STATE',
}
