name: Build, lint and test
on: [push]
jobs:
  build-lint-test:
    name: build lint test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.21.0'
          cache: 'yarn'

      - name: Install npm packages
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run lint
        run: yarn lint

      - name: Run tests for client
        run: yarn test --watchAll=false
